### ISSUE TITLE
Missing .env instructions

### ISSUE THREAD

**Issue by beauremus** [React-Automation-Studio/React-Automation-Studio-Alarm-Handler-Standalone#1]
I attempted to follow the installation instructions in the [README](https://github.com/wduckitt/React-Automation-Studio-Alarm-Handler-Standalone/blob/master/README.md) but was held up by `.env` not existing. It looks like the [README](https://github.com/wduckitt/React-Automation-Studio/blob/master/README.md) from the [main project](https://github.com/wduckitt/React-Automation-Studio) has accounted for this with the added instruction `touch .env`. Is that the correct procedure to get going?

I copied [example.env](https://github.com/wduckitt/React-Automation-Studio-Alarm-Handler-Standalone/blob/master/example.env) to `.env` and that worked.

**Comment by justinabraham** [comment]
Thank you for pointing that out. Yes I've update README to copy example.env to .env - this will work fine.
