### ISSUE TITLE
Docker memory limit can prevent npm build

### ISSUE THREAD

**Issue by beauremus** [React-Automation-Studio/React-Automation-Studio-Alarm-Handler-Standalone#2]
I'm on macOS using the Docker desktop client and ran into an issue of NodeJS running out of memory. I noticed the explicit `--max_old_space_size=4096` so I started digging. I started by doubling the allowed size, but that wasn't the problem. I found that the resources available to Docker were set 2GB of memory. It could be that I adjusted this limit below the default at some point, but I thought you'd like to know about this hurdle if others hit it.

<details>
<summary>Stack trace</summary>
<pre>
------
 > [11/11] RUN npm run build:
#15 0.534
#15 0.534 > react-automation-studio@3.0.0 build /frontend
#15 0.534 > react-scripts --max_old_space_size=4096 build
#15 0.534
#15 2.988 Creating an optimized production build...
#15 67.86 The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
#15 68.10 npm ERR! code ELIFECYCLE
#15 68.10 npm ERR! errno 1
#15 68.12 npm ERR! react-automation-studio@3.0.0 build: `react-scripts --max_old_space_size=4096 build`
#15 68.13 npm ERR! Exit status 1
#15 68.13 npm ERR!
#15 68.13 npm ERR! Failed at the react-automation-studio@3.0.0 build script.
#15 68.13 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#15 68.82
#15 68.82 npm ERR! A complete log of this run can be found in:
#15 68.82 npm ERR!     /root/.npm/_logs/2021-06-01T17_59_24_856Z-debug.log
------
executor failed running [/bin/sh -c npm run build]: exit code: 1
ERROR: Service 'frontend' failed to build
</pre>
</details>

**Comment by justinabraham** [comment]
Hi @beauremus , this issues has been discussed [here](https://github.com/wduckitt/React-Automation-Studio/issues/23#issuecomment-816494453)
